apiVersion: v1
kind: Service
metadata:
  name: ingestion-server
  labels:
    app: ingestion-server
spec:
  ports:
  - protocol: UDP
    port: 6666
    targetPort: 6666
  selector:
    app: imagine2022-ingestion
    deploymentconfig: imagine2022-ingestion

  type: NodePort
